In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
x=np.array([1,2,3,1,2,3])

In [4]:
x

array([1, 2, 3, 1, 2, 3])

In [5]:
x.ndim

1

In [8]:
x[5]

3

In [11]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
y.ndim

2

In [14]:
y.shape

(3, 3)

In [22]:
z=np.arange(1,25)

In [23]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [24]:
z.ndim

1

In [25]:
z.shape


(24,)

In [30]:
z2=z.reshape(4,3,2)

In [31]:
z2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [32]:
np.reshape?